export const PATHS = {
  HOME: '/',
  ADD_FUNDS: '/add-funds',
  HISTORY: '/history',
  CHANGE_PASSWORD: '/change-password',
  MAILBOX_INBOX: '/mailbox-inbox',
  MAILBOX_OUTBOX: '/mailbox-outbox',
  MAILBOX_SENTBOX: '/mailbox-sentbox',
  MAILBOX_POST: '/mailbox-post',
  ABOUT: '/about',
  TERMS_CONDITIONS: '/terms',
  PRIVACY_POLICY: '/privacy-policy',
  REFUND_POLICY: '/refund_policy',
  OUR_SERVICE: '/our-service',
  FAQ: '/questions',
  JOB: '/job',
  CONTACT: '/contact',
}
